### ISSUE TITLE
Function to_empty() does not expect kwarg exp

### ISSUE THREAD

**Issue by Mojken** [roguh/i3empty#1]
Added to kwargs here:
https://github.com/roguh/i3empty/blob/4dc6c34846661dfd5cd1f5e72515662b2ec88548/i3empty.py#L83-L85

And passed to to_empty() here:
https://github.com/roguh/i3empty/blob/4dc6c34846661dfd5cd1f5e72515662b2ec88548/i3empty.py#L93

This crashes the program on my machine, running Python 3.7.3.

**Comment by pedrovictori** [comment]
I can confirm that this also crashes the program on my machine, running Python 3.9.6, and it is fixed by #2

**Comment by roguh** [comment]
Thank you for the reports, you guys! I merged @Mojken 's PR just now. Let me know if there's any improvements you'd like to see.
